import "dotenv/config";
import Fastify from "fastify";
import {WebSocketServer,WebSocket} from "ws";
import type {RawData} from "ws";
import type {IncomingMessage} from "node:http";
import {randomUUID} from "node:crypto";
import {isAudioContentType,isMessageId,messageCatalog,type AudioAsset,type MessageId} from "@gaitwatcher/shared";
import {AudioStorage} from "./storage.js";

type State="requested"|"agent_received"|"camera_playback_started"|"completed"|"failed";
type Command={id:string;agentId:string;deviceId:string;messageId?:MessageId;assetId?:string;state:State;error?:string;updatedAt:string;history:{state:State;at:string;error?:string}[]};
type PendingAsset={asset:AudioAsset};
const token=process.env.REMOTE_CONTROL_TOKEN;if(!token)throw new Error("REMOTE_CONTROL_TOKEN is required");
const storage=new AudioStorage(),commands=new Map<string,Command>(),agents=new Map<string,WebSocket>(),pendingAssets=new Map<string,PendingAsset>();
const authorized=(value:string|undefined)=>value===`Bearer ${token}`;
const requireAuth=(authorization:string|undefined,reply:any)=>{if(authorized(authorization))return true;reply.code(401).send({error:"unauthorized"});return false};
const safeName=(value:unknown)=>typeof value==="string"&&value.trim().length>0&&value.trim().length<=80?value.trim():undefined;
const getAsset=async(id:string)=> (await storage.list()).find(asset=>asset.id===id);

const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>GaitWatcher</title><style>body{font:16px system-ui;max-width:700px;margin:2rem auto;padding:0 1rem}button,input{margin:.25rem;padding:.45rem}#o{white-space:pre-wrap;background:#f4f4f4;padding:1rem}li{margin:.5rem 0}</style><main><h1>GaitWatcher</h1><p id=agent>Home Agent: checking…</p><p>Development proof only. Enter the temporary control token.</p><input id=t type=password placeholder="Control token"><h2>Quick messages</h2><div>${Object.entries(messageCatalog).map(([id,m])=>`<button data-message="${id}">${m.label}</button>`).join("")}</div><h2>Record a message</h2><input id=n maxlength=80 placeholder="Name (for example, Medication reminder)"><div><button id=record>Start recording</button><button id=stop disabled>Stop</button><button id=cancel disabled>Discard</button></div><p id=recording></p><audio id=preview controls hidden></audio><button id=save disabled>Save recording</button><h2>Saved recordings</h2><ul id=assets></ul><pre id=o></pre><script>
const q=s=>document.querySelector(s),out=q('#o'),token=()=>q('#t').value,agent=q('#agent'),assets=q('#assets');let recorder,stream,parts=[],blob;
const auth=()=>({authorization:'Bearer '+token()});
async function online(){let r=await fetch('/agents/dev-home-agent'),j=await r.json();agent.textContent='Home Agent: '+(j.online?'online':'offline')+' · Living room camera'}online();setInterval(online,2000);
async function command(body){let r=await fetch('/commands',{method:'POST',headers:{'content-type':'application/json',...auth()},body:JSON.stringify({agentId:'dev-home-agent',deviceId:'living-room-reolink',...body})}),c=await r.json();out.textContent=JSON.stringify(c.history??c,null,2);if(!c.id)return;let x=setInterval(async()=>{let s=await fetch('/commands/'+c.id,{headers:auth()}),j=await s.json();out.textContent=JSON.stringify(j.history??j,null,2);if(['completed','failed'].includes(j.state))clearInterval(x)},500)}
document.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>command({messageId:b.dataset.message}));
async function refresh(){let r=await fetch('/audio-assets',{headers:auth()});if(!r.ok){assets.textContent=token()?'Unable to load recordings.':'Enter the token to see recordings.';return}let j=await r.json();assets.replaceChildren(...j.assets.map(a=>{let li=document.createElement('li'),play=document.createElement('button'),del=document.createElement('button');li.append(document.createTextNode(a.name+' ('+Math.ceil(a.sizeBytes/1024)+' KB) '));play.textContent='Play';play.onclick=()=>command({assetId:a.id});del.textContent='Delete';del.onclick=async()=>{if(confirm('Delete '+a.name+'?')){await fetch('/audio-assets/'+a.id,{method:'DELETE',headers:auth()});refresh()}};li.append(play,del);return li}))}q('#t').addEventListener('change',refresh);
q('#record').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});let type=['audio/webm','audio/mp4','audio/ogg'].find(MediaRecorder.isTypeSupported);recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);parts=[];recorder.ondataavailable=e=>parts.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());blob=new Blob(parts,{type:recorder.mimeType||'audio/webm'});q('#preview').src=URL.createObjectURL(blob);q('#preview').hidden=false;q('#save').disabled=false;q('#recording').textContent='Recording ready: '+Math.ceil(blob.size/1024)+' KB';q('#record').disabled=false;q('#stop').disabled=true;q('#cancel').disabled=true};recorder.start();q('#recording').textContent='Recording…';q('#record').disabled=true;q('#stop').disabled=false;q('#cancel').disabled=false;setTimeout(()=>recorder?.state==='recording'&&recorder.stop(),60000)}catch(e){q('#recording').textContent='Microphone access failed: '+e.message}};
q('#stop').onclick=()=>recorder?.state==='recording'&&recorder.stop();q('#cancel').onclick=()=>{parts=[];blob=undefined;if(recorder?.state==='recording')recorder.stop();q('#preview').hidden=true;q('#save').disabled=true};
q('#save').onclick=async()=>{if(!blob)return;let name=q('#n').value.trim()||'Voice message';q('#save').disabled=true;try{let r=await fetch('/audio-assets/upload-urls',{method:'POST',headers:{'content-type':'application/json',...auth()},body:JSON.stringify({name,contentType:blob.type,sizeBytes:blob.size})}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not prepare upload');let put=await fetch(j.uploadUrl,{method:'PUT',headers:{'content-type':blob.type},body:blob});if(!put.ok)throw Error('Upload failed');r=await fetch('/audio-assets/'+j.asset.id+'/finalize',{method:'POST',headers:auth()});j=await r.json();if(!r.ok)throw Error(j.error||'Could not save recording');q('#recording').textContent='Saved.';blob=undefined;q('#preview').hidden=true;refresh()}catch(e){q('#recording').textContent=e.message;q('#save').disabled=false}};
</script></main>`;

const app=Fastify({logger:false});
app.get("/",async(_,reply)=>reply.type("text/html").send(html));
app.get("/health",async()=>({ok:true,agentsOnline:agents.size}));
app.get("/agents/:id",async(req)=>({agentId:(req.params as any).id,online:agents.has((req.params as any).id)}));
app.get("/audio-assets",async(req,reply)=>{if(!requireAuth(req.headers.authorization,reply))return;return {assets:await storage.list()}});
app.post("/audio-assets/upload-urls",async(req,reply)=>{if(!requireAuth(req.headers.authorization,reply))return;const body=req.body as any,name=safeName(body?.name),contentType=body?.contentType,sizeBytes=body?.sizeBytes;if(!name||!isAudioContentType(contentType)||!Number.isInteger(sizeBytes)||sizeBytes<1||sizeBytes>10*1024*1024)return reply.code(400).send({error:"name, supported audio contentType, and sizeBytes up to 10 MB are required"});const asset:AudioAsset={id:randomUUID(),name,contentType,sizeBytes,createdAt:new Date().toISOString()};pendingAssets.set(asset.id,{asset});return {asset,uploadUrl:await storage.uploadUrl(asset.id,asset.contentType)}});
app.post("/audio-assets/:id/finalize",async(req,reply)=>{if(!requireAuth(req.headers.authorization,reply))return;const id=(req.params as any).id,pending=pendingAssets.get(id);if(!pending)return reply.code(404).send({error:"unknown or expired upload"});try{await storage.finalize(pending.asset);pendingAssets.delete(id);return {asset:pending.asset}}catch(error){return reply.code(400).send({error:error instanceof Error?error.message:"upload validation failed"})}});
app.delete("/audio-assets/:id",async(req,reply)=>{if(!requireAuth(req.headers.authorization,reply))return;const asset=await getAsset((req.params as any).id);if(!asset)return reply.code(404).send({error:"unknown recording"});await storage.delete(asset);return reply.code(204).send()});
app.post("/commands",async(req,reply)=>{if(!requireAuth(req.headers.authorization,reply))return;const body=req.body as any;if(!body||typeof body.agentId!=="string"||typeof body.deviceId!=="string"||((!isMessageId(body.messageId))===(! (typeof body.assetId==="string"))))return reply.code(400).send({error:"agentId, deviceId, and exactly one of messageId or assetId are required"});let asset:AudioAsset|undefined;if(typeof body.assetId==="string"){asset=await getAsset(body.assetId);if(!asset)return reply.code(404).send({error:"recording not found"})}const at=new Date().toISOString(),command:Command={id:randomUUID(),agentId:body.agentId,deviceId:body.deviceId,...(asset?{assetId:asset.id}:{messageId:body.messageId}),state:"requested",updatedAt:at,history:[{state:"requested",at}]};commands.set(command.id,command);const agent=agents.get(command.agentId);if(!agent){command.state="failed";command.error="agent not connected";command.updatedAt=new Date().toISOString();command.history.push({state:"failed",at:command.updatedAt,error:command.error})}else{const payload=asset?{type:"play_asset",commandId:command.id,deviceId:command.deviceId,downloadUrl:await storage.downloadUrl(asset)}:{type:"play",commandId:command.id,deviceId:command.deviceId,messageId:command.messageId};agent.send(JSON.stringify(payload))}return reply.code(202).send(command)});
app.get("/commands/:id",async(req,reply)=>{if(!requireAuth(req.headers.authorization,reply))return;const command=commands.get((req.params as any).id);return command??reply.code(404).send({error:"unknown command"})});
const wsServer=new WebSocketServer({noServer:true});wsServer.on("connection",(socket:WebSocket,_request:IncomingMessage,agentId:string)=>{agents.set(agentId,socket);socket.on("close",()=>agents.get(agentId)===socket&&agents.delete(agentId));socket.on("message",(raw:RawData)=>{try{const message=JSON.parse(String(raw));if(message.type!=="status"||typeof message.commandId!=="string"||!["agent_received","camera_playback_started","completed","failed"].includes(message.state))return;const command=commands.get(message.commandId);if(!command||command.agentId!==agentId)return;command.state=message.state;command.updatedAt=new Date().toISOString();if(typeof message.error==="string")command.error=message.error;command.history.push({state:command.state,at:command.updatedAt,...(command.error?{error:command.error}:{})})}catch{}})});
app.server.on("upgrade",(request,socket,head)=>{const url=new URL(request.url??"/","http://localhost");if(url.pathname!=="/agent"||!url.searchParams.get("agentId")){socket.destroy();return}wsServer.handleUpgrade(request,socket,head,ws=>wsServer.emit("connection",ws,request,url.searchParams.get("agentId")))});
await app.listen({host:process.env.REMOTE_CONTROL_HOST??"0.0.0.0",port:Number(process.env.PORT??process.env.REMOTE_CONTROL_PORT??3100)});
