import Fastify from "fastify";
import cors from "@fastify/cors";
import {PrismaClient, Provider, EventStatus} from "@prisma/client";
import {MemoryQueue} from "../../../packages/queue/src/index.js";
import {providerFor} from "../../../packages/camera-providers/src/index.js";
import type {CvResult} from "../../../packages/domain/src/index.js";

export const prisma=new PrismaClient();
const queue=new MemoryQueue(); const maxRetries=3;
const safeError=(e:unknown)=>e instanceof Error?e.message.replace(/https?:\/\/\S+/g,"[redacted-url]"):"unknown error";
async function cv(mediaPath?:string){ const url=process.env.CV_WORKER_URL??"http://localhost:8000"; const r=await fetch(`${url}/detect`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mediaPath,sampleFps:Number(process.env.CV_SAMPLE_FPS??1)})}); if(!r.ok)throw new Error(`CV worker ${r.status}`); return r.json() as Promise<CvResult> }
async function processJob({eventId}:{eventId:string}) { const started=Date.now(); const event=await prisma.cameraEvent.findUnique({where:{id:eventId},include:{device:true}}); if(!event||event.status===EventStatus.SUCCEEDED)return; if(event.attempts>=maxRetries){await prisma.cameraEvent.update({where:{id:eventId},data:{status:EventStatus.DEAD_LETTER}});return} await prisma.cameraEvent.update({where:{id:eventId},data:{status:EventStatus.PROCESSING,attempts:{increment:1}}}); let temporaryBytes=0;
 try { const media=await providerFor(event.provider.toLowerCase()).getEventMedia(event.providerEventId); const result=await cv(media.localPath); const resident=await prisma.resident.findFirst({where:{householdId:event.device.householdId}}); if(!resident)throw new Error("No resident for household"); await prisma.$transaction([prisma.observation.upsert({where:{eventId},create:{eventId,residentId:resident.id,deviceId:event.deviceId,type:result.personDetected&&result.poseDetected?"body_state":result.personDetected?"person_detected":"no_person_detected",confidence:result.bodyStateConfidence||result.personConfidence,timestamp:event.occurredAt,metadata:{state:result.bodyState,poseDetected:result.poseDetected,poseConfidence:result.poseConfidence,framesAnalyzed:result.framesAnalyzed,framesDecoded:result.framesDecoded,providerMediaId:media.providerMediaId}},update:{}}),prisma.processingMetrics.upsert({where:{eventId},create:{eventId,provider:event.provider,mediaBytesDownloaded:temporaryBytes,framesDecoded:result.framesDecoded,framesAnalyzed:result.framesAnalyzed,framesSentToPersonDetector:result.framesSentToPersonDetector,framesSentToPoseModel:result.framesSentToPoseModel,personDetectionMs:result.personDetectionMs,poseInferenceMs:result.poseInferenceMs,bodyStateClassificationMs:result.bodyStateClassificationMs,cvProcessingMs:result.totalProcessingMs,totalJobMs:Date.now()-started,temporaryBytesRetained:0},update:{}}),prisma.cameraEvent.update({where:{id:eventId},data:{status:EventStatus.SUCCEEDED,processedAt:new Date(),error:null}})]);
 } catch(e) { const next=await prisma.cameraEvent.update({where:{id:eventId},data:{status:EventStatus.FAILED,error:safeError(e)}}); if(next.attempts<maxRetries) await queue.enqueue({eventId}); else await prisma.cameraEvent.update({where:{id:eventId},data:{status:EventStatus.DEAD_LETTER}}); }
}
queue.consume(processJob);
export async function buildApp(){const app=Fastify({logger:false}); await app.register(cors,{origin:true});
 app.post("/v1/events",async(req,reply)=>{const b=req.body as any; if(!b?.provider||!b?.providerEventId||!b?.deviceId||!b?.occurredAt)return reply.code(400).send({error:"provider, providerEventId, deviceId and occurredAt are required"}); if(!["mock","ring"].includes(b.provider))return reply.code(400).send({error:"unsupported provider"}); const device=await prisma.cameraDevice.findUnique({where:{id:b.deviceId}}); if(!device)return reply.code(404).send({error:"camera device not found"}); if(device.provider!==b.provider.toUpperCase())return reply.code(400).send({error:"device/provider mismatch"}); const key=`${b.provider}:${b.providerEventId}`; const existing=await prisma.cameraEvent.findUnique({where:{idempotencyKey:key}}); if(existing)return reply.code(202).send({eventId:existing.id,duplicate:true,status:existing.status}); const event=await prisma.cameraEvent.create({data:{idempotencyKey:key,deviceId:b.deviceId,provider:b.provider.toUpperCase(),providerEventId:b.providerEventId,mediaId:b.mediaId??b.providerEventId,occurredAt:new Date(b.occurredAt)}}); await queue.enqueue({eventId:event.id}); return reply.code(202).send({eventId:event.id,duplicate:false,status:event.status}); });
 app.get("/v1/households/:householdId/timeline",async(req,reply)=>{const {householdId}=req.params as any; const userId=req.headers["x-user-id"] as string; if(!userId)return reply.code(401).send({error:"x-user-id required"}); const membership=await prisma.caregiverMembership.findUnique({where:{userId_householdId:{userId,householdId}}}); if(!membership)return reply.code(403).send({error:"not a caregiver for household"}); return prisma.observation.findMany({where:{resident:{householdId}},include:{resident:true},orderBy:{timestamp:"desc"}}); });
 app.get("/internal/metrics",async()=>{const rows=await prisma.processingMetrics.findMany(); const n=rows.length, avg=(key:keyof typeof rows[number])=>n?rows.reduce((s,r)=>s+Number(r[key]),0)/n:0; const lat=rows.map(x=>x.totalJobMs).sort((a,b)=>a-b); const pct=(p:number)=>lat[Math.max(0,Math.ceil(lat.length*p)-1)]??0; const events=await prisma.cameraEvent.groupBy({by:["status"],_count:true}); return {jobsProcessed:n,successRate:n?events.find(x=>x.status==="SUCCEEDED")?._count!/n:0,failureRate:n?events.filter(x=>["FAILED","DEAD_LETTER"].includes(x.status)).reduce((s,x)=>s+x._count,0)/n:0,averageMediaBytes:avg("mediaBytesDownloaded"),averageFramesAnalyzed:avg("framesAnalyzed"),averagePersonDetectionMs:avg("personDetectionMs"),averagePoseInferenceMs:avg("poseInferenceMs"),averageTotalCvMs:avg("cvProcessingMs"),p50ProcessingLatencyMs:pct(.5),p95ProcessingLatencyMs:pct(.95),queueDepth:queue.depth()}; }); return app; }
